version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - './frontend:/usr/src/frontend'
      - '/usr/src/frontend/node_modules'
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8000:8000
    volumes:
      - './server:/usr/src/server'
      - '/usr/src/server/node_modules'
